mysite/accounts/urls.py
from django.urls import path
from .views import SignUpView
from . import views

urlpatterns = [
	path('account/<int:pk>/', views.account, name = 'account'),
	path('signup/', SignUpView.as_view(), name = 'signup'),
	
] 

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
	path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
	path('', include('mainApp.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/', include('accounts.urls')),
	path('login/', views.LoginView.as_view(), name = 'login'),
	path('news/', include('news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG: 
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	
	

mysite/news/urls.py
from . import views    # news
from django.urls import path

app_name = 'news'  # ВАЖНО ДЛЯ ПРАВИЛЬНОГО ОБРАЩЕНИЯ ПО ПСЕВДОНИМУ
urlpatterns = [
	path('', views.news_home, name = "news_home"),  # Смотрит куда дальше нам нужно, параметр name именнованая ссылка / псевдрним
	path('create/', views.create, name = "create"),
	path('<int:articles_id>/', views.detailview, name = 'detailview'), # Отслеживаем динам параметр. 
	path('<int:articles_id>/<int:articles_id2>/', views.redaction, name = 'redaction'),
	path('delete/<int:articles_id3>/', views.delete_article, name = 'delete_article'),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

class AuthUserForm(forms.ModelForm, AuthenticationForm):
	class Meta:
		model = User
		fields = ['username', 'password']

mysite/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import AuthUserForm
from news.models import Articles                                              
from django.http import Http404

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.views import LoginView
# Create your views here.

#Регистрация
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('mainApp:home')
    template_name = 'signup.html'

#Авторизация
class LoginUpView(LoginView):
	template_name = 'login.html'
	form_class = AuthUserForm  
	success_url = reverse_lazy('mainApp:home')


# Аккаунт
def account(request, pk):
	try:
		access = False
		our_articles_list = Articles.objects.filter(id_user = pk)	
		if request.user.id == pk:
			access = True
	except:
		raise Http404("404")	
	data = {
		'our_articles_list': our_articles_list , 
		'access': access ,
	}

	return render(request, 'accounts.html', data)
		
	

mysite/accounts/templates/accounts.html
{% extends "mainApp/wrapper.html" %}  <!-- Можем наследовать из другой папки, п. ч. Django объеденяет templates -->

{% block title %} Аккаунт  {% endblock %}

{% block content %}

{{ request.user }}<br>
<h1>Мои новости</h1>
{% for e in our_articles_list %}
	<a href="{% url 'news:detailview' e.id %}">{{ e.title }}</a><br>
	{% if access %}
	<button  style="background-color: orange"><a href="{% url 'news:redaction' e.id e.id %}"> Редактирование</a></button><br> 
	<button  style="background-color: red"><a href="{% url 'news:delete_article' e.id %}"> Удаление статьи</a></button><br>
	{% endif %}
{% endfor %}	
<h1>Сохры</h1>		

				
				
{% endblock %}					 
				

mysite/accounts/templates/signup.html
<!-- Регистрация -->
{% extends "mainApp/wrapper.html" %}
 
{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  <div>
  	{{ form.as_p }}
  </div>
  <button type="submit"> Sign up</button>
</form>
{% endblock content %}