mysite/mainApp/urls.py
from django.urls import path
from . import views

app_name = 'mainApp'
urlpatterns = [
	path('', views.index, name = "home"),
	path('about/', views.about, name = "about"),
	path('contact/', views.contact, name = "contact"),
	path('registration/', views.registration, name = 'registration'),
	path('registration2/', views.registration2, name = 'registration2'),
	path('authorization/', views.authorization, name = 'authorization'),
	
]	

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
	path('grappelli/', include('grappelli.urls')), # grappelli URLS
    path('admin/', admin.site.urls),
	path('', include('mainApp.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/', include('accounts.urls')),
	path('login/', views.LoginView.as_view(), name = 'login'),
	path('news/', include('news.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG: 
	urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	
	

mysite/news/urls.py
from . import views    # news
from django.urls import path

app_name = 'news'  # ВАЖНО ДЛЯ ПРАВИЛЬНОГО ОБРАЩЕНИЯ ПО ПСЕВДОНИМУ
urlpatterns = [
	path('', views.news_home, name = "news_home"),  # Смотрит куда дальше нам нужно, параметр name именнованая ссылка / псевдрним
	path('create/', views.create, name = "create"),
	path('<int:articles_id>/', views.detailview, name = 'detailview'), # Отслеживаем динам параметр. 
	path('<int:articles_id>/<int:articles_id2>/', views.redaction, name = 'redaction'),
	path('delete/<int:articles_id3>/', views.delete_article, name = 'delete_article'),
]

mysite/mainApp/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.
class Registration(models.Model):
	name = models.CharField('Имя', max_length = 20)
	surname = models.CharField('Фамилия', max_length = 20)
	password = models.CharField('Пароль', max_length = 15, default = 'admin')  # Нужно было умолчание, из-за отстутвия паролей у предыдущих пользователей
	age = models.IntegerField('Возраст')
	date = models.DateTimeField('Дата регистрации')

	def __str__(self):
		return self.name

	def difference_time(self):      #3  Разница времени True / False
		return self.date >= (timezone.now() - datetime.timedelta(days = 7))

	def time_now():	   ## Дата сейчас
		return timezone.datetime.now()

	class Meta:
		verbose_name = 'Регистрация'
		verbose_name_plural = 'Регистрации'

class Registration2(models.Model):
	name = models.CharField('Имя', max_length = 20)
	surname = models.CharField('Фамилия', max_length = 20)
	password = models.CharField('Пароль', max_length = 15, default = 'admin')  # Нужно было умолчание, из-за отстутвия паролей у предыдущих пользователей
	age = models.IntegerField('Возраст')
	date = models.DateTimeField('Дата регистрации')

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'Регистрация2'
		verbose_name_plural = 'Регистрации2'

mysite/mainApp/forms.py
from .models import Registration, Registration2
from django import forms
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea

class RegistrationForm(ModelForm):
	class Meta:
		model = Registration  # С каким моделью иы работаем
		fields = ['name', 'surname', 'password', 'age', 'date'] # Наши поля

		widgets = {       # Прописмываем харак-ки для каждого отдельного поля
			'name': TextInput(attrs = {
				'class': 'form-control',
				'placeholder': 'Имя',
				}),
			'surname': TextInput(attrs = {
				'class': 'form-control',
				'placeholder': 'Фамилия',
				}),	
			'password': TextInput(attrs = {
				'class': 'form-control',
				'placeholder': 'Пароль',
				}),	
			'age': TextInput(attrs = {
				'class': 'form-control',
				'placeholder': 'Возраст',
				}),
			'date': DateTimeInput(attrs = {
				'class': 'form-control',
				'placeholder': 'Дата регистрации',
				}),
		}	



# class Registration2Form(forms.ModelForm):
# 	class Meta:
# 		model = Registration2
# 		fields = ['name', 'surname', 'password', 'age', 'date']

mysite/mainApp/views.py
from django.shortcuts import render, redirect
from .models import Registration, Registration2
from .forms import RegistrationForm

# Create your views here.
def index(request):
	data = {
		'title' : 'Главная стр!!!!',
		'sto_num': 'wktieht' ,
		'obj': {
					'car': 'BMW',
					'age': '18',
					'hobby': 'programmist'	
				}
	}
	return render(request, 'mainApp/homePage.html', data)
	

def about(request):
	return render(request, 'mainApp/aboutMe.html')

def contact(request):
	return render(request, 'mainApp/ourContact.html')	
#НЕ СМОРТИТЕ НЕ НУЖНО
def registration(request):    # Регистрация вместе с проверкой на #
	check_name = True
	error = ''
	##############################################
	# b = Registration.objects.filter(name__startswith = 'Ами') # совпадение нач букв
	# spis = [e.name for e in Registration.objects.all() if True]
	# a = Registration.objects.get( id = 19 )
	# b = a.difference_time()
	###############################################	
	if request.method == 'POST':
		form = RegistrationForm(request.POST)  #
		a = form.data.get("name")
		if form.is_valid():
			for e in Registration.objects.all():
				if a != e.name:
					continue
				else:
					error = "Имя уже занято"
					check_name = False
					break
			if check_name:
				form.save()
						
		else:
			error = 'Форма была неверной'	

	form = RegistrationForm()
	data = {
		'form': form ,
		'error': error ,
		
		
	}
	return render(request, 'mainApp/registration.html', data)		
	
	
			
#НЕ СМОРТИТЕ НЕ НУЖНО
def registration2(request):    # Регистрация вместе с проверкой на идентичность
	error = ''
	check_name = True
	#z = Registration2.objects.get(id = 12)
	if request.method == 'POST':
		for obj in Registration2.objects.all():
			if request.POST['name'] == obj.name:
				error = 'Имя уже занято'
				check_name = False
				break
			else:
				continue
		if check_name:	
			b = Registration2(name = request.POST['name'],  surname = request.POST['surname'], password = request.POST['password'], age = request.POST['age'], date = Registration.time_now())
			b.save()
			error = 'Регистрация успешна выполнена'	
					
	data = {
		'error': error ,
		#'z': z ,
		
	}

	return render(request, 'mainApp/registration2.html', data)
#НЕ СМОРТИТЕ НЕ НУЖНО
def authorization(request):
	error = ''
	if request.method == 'POST':
		
		for obj in Registration2.objects.all():
			if (request.POST['name'] == obj.name) and (request.POST['password'] == obj.password):
				return redirect('mainApp:home')
			else:
				continue
		error = 'Логин и пароль введены не коректно'					
				
	data = {
		'error': error ,
	}	
		
	return render(request, 'mainApp/authorization.html', data)		
			
	
			

					
			

	
		
		

		
	
	
	


	
		
					
		
		
		

		





	


			

mysite/mainApp/templates/mainApp/aboutMe.html
{% extends "mainApp/wrapper.html" %} 

{% block title %} aoutMe {% endblock %}

{% block content %}
<b> Me inf </b>
{% endblock %}

mysite/mainApp/templates/mainApp/authorization.html
{% extends "mainApp/wrapper.html" %}  <!-- Можем наследовать из другой папки, п. ч. Django объеденяет templates -->

{% block title %} Вход {% endblock %}

{% block content %}

	<div>
		<h1 class="a">Вход</h1>
		<form action="{% url 'mainApp:authorization' %}" method="POST">
			{% csrf_token %} <!-- Для безопасной отправки, ОБЯЗАТЕЛЬНО В КАЖДОЙ ФОРМЕ -->
			<input type="text" name="name"  class="form-control" placeholder="Имя"><br>
			<input type="password" name="password" class="form-control" placeholder="Пароль"><br>
			{{ error }}<br>
			<button class="btn btn-success" type="submit">Вход</button>
		</form>		
	</div>	 
		
{% endblock %}	
		
			
			
			

mysite/mainApp/templates/mainApp/homePage.html
{% extends "mainApp/wrapper.html" %}   <!-- Связываем наш html файл с шаблонизоторм -->
<!-- Название блока важно -->	
{% block title %} {{ title }} {% endblock %}

{% block content %}
<b> {{ title }} </b>	 <!-- Передча данных в нащ html для отображения -->

{% for i in values %}
	{% if i == "Igor" %}
		{% filter upper %}  <!-- зарезервированный filter 'upper' -->
			<p>{{ i }}</p>
		{% endfilter %}
	{% endif %}
{% endfor %}

{% for key in obj %}
	<p>{{key}}</p>
{% endfor %}

уыно9эзгш49знго9р8ще458щ45не8щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45щ45

{% endblock %}

mysite/mainApp/templates/mainApp/ourContact.html
{% extends "mainApp/wrapper.html" %} 

{% block title %} Контакты {% endblock %}

{% block content %}
<b> Me contact </b>
{% endblock %}

mysite/mainApp/templates/mainApp/registration.html
{% extends "mainApp/wrapper.html" %}  <!-- Можем наследовать из другой папки, п. ч. Django объеденяет templates -->

{% block title %} Регистрация {% endblock %}

{% block content %}

	<div>
		<h1 class="a">Регистрация</h1>
		<form method="POST">
			{% csrf_token %} <!-- Для безопасной отправки, ОБЯЗАТЕЛЬНО В КАЖДОЙ ФОРМЕ -->
			{{ form.name }}<br>  <!-- Выводим объект из вьюшки. Наше поле -->
			{{ form.surname }}<br>
			{{ form.password }}<br>
			{{ form.age }}<br>
			{{ form.date }}<br>
			
			<span>{{ error }}</span><br>
			<span>{{ spis }}</span><br>
			<span>{{ a }}</span><br>
			<span>{{ b }}</span><br>
			<button class="btn btn-success" type="submit">Зарегистрироваться</button>
			
		</form>	
	</div>	 
		
{% endblock %}	

mysite/mainApp/templates/mainApp/registration2.html
{% extends "mainApp/wrapper.html" %}  <!-- Можем наследовать из другой папки, п. ч. Django объеденяет templates -->

{% block title %} Регистрация {% endblock %}

{% block content %}

	<div>
		<h1 class="a">Регистрация</h1>
		<form action="{% url 'mainApp:registration2' %}" method="POST">
			{% csrf_token %} <!-- Для безопасной отправки, ОБЯЗАТЕЛЬНО В КАЖДОЙ ФОРМЕ -->
			<input type="text" name="name" required="Заполните это поле" class="form-control" placeholder="Имя"><br>
			<input type="text" name="surname" required="" class="form-control" placeholder="Фамилия"><br>
			<input type="password" name="password" required="" class="form-control" placeholder="Пароль"><br>
			<input type="text" name="age" required="" class="form-control" placeholder="Возраст"><br>
			
			{{ error }}<br>
			
			<button  class="btn btn-success" type="submit">Зарегистрироваться</button>
		</form>	
			<button  class="btn btn-success" type="submit"> <a href="{% url 'mainApp:authorization' %}">Авторизация</a></button>
	</div>	 
		
{% endblock %}	

			
			
	

mysite/mainApp/templates/mainApp/wrapper.html
{% load static %}   <!-- Подключаем static файлы --> 
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>{% block title %}mysite {% endblock %}</title>
	
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> <!-- Bootstrap -->
	<link rel="stylesheet" type="text/css" href="{% static 'mainApp/css/main.css' %}">
	<link rel="stylesheet" type="text/css" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"> <!--Font Awesome  -->  
</head>
<body >
	<aside>
		
		<span class="logo"> mysite </span>
		<h3>Навигация</h3>
		<ul>
			<a href="{% url 'mainApp:home' %}"><li><i class="fas fa-home"></i> Главная</li></a>  <!-- Использоваем jinja стр-ру для перехода ро ссылкам, но можно и без jinja  -->
			{% if request.user.is_authenticated %}
			<a href="{% url 'account' request.user.id %}"><li><i class="far fa-newspaper"></i> Аккаунт</li></a>
			<a href="{% url 'account' request.user.id %}"><li><i class="far fa-newspaper"></i> {{ request.user }}</li></a>
			{% endif %}
			<a href="{% url 'news:news_home' %}"><li><i class="far fa-newspaper"></i> Новости</li></a>
			<a href="{% url 'mainApp:about' %}"><li><i class="fas fa-info-circle"></i> Про нас</li></a>
			<a href="{% url 'mainApp:contact' %}"><li><i class="fas fa-address-card"></i> Контакты</li></a>
			<a href="{% url 'mainApp:registration' %}"><li><i class="fas fa-database"></i> Регистрация</li></a>
			<a href="{% url 'mainApp:registration2' %}"><li><i class="fas fa-database"></i> Регистрация2</li></a>
			<a href="{% url 'mainApp:authorization' %}"><li><i class="fas fa-database"></i> Вход</li></a>
			<a href="{% url 'signup' %}"><li><i class="fas fa-database"></i> Регистрация_другая</li></a>
			<a href="{% url 'login' %}"><li><i class="fas fa-database"></i> Авторизация_другая</li></a>
			<a href="{% url 'news:create' %}"><li><button class="btn btn-info"><i class="fas fa-plus-circle"></i> Добавление статьи</button></li></a>

		</ul>
	</aside>
	<main>
	{% block content %}  <!-- Шаблонизатор jinja -->
	<!-- sam kod -->
	{% endblock %}	
	</main>
</body>
</html>	